
#     version: "3.1"

# services:
#   reverse_proxy:
#     image: cloaiza/reverse_proxy
#     user: nginx

#   database:
#     image: cloaiza/database
#     user: postgres
#     environment:
#       POSTGRES_USER: gordonuser
#       POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
#       POSTGRES_DB: atsea
#     ports:
#       - "5432:5432" 
#     networks:
#       - back-tier
#     secrets:
#       - postgres_password

#   appserver:
#     image: cloaiza/app
#     user: gordon
#     ports:
#       - "8080:8080" 
#       - "5005:5005"
#     networks:
#       - front-tier
#       - back-tier
#     secrets:
#       - postgres_password

#   payment_gateway:
#     image: cloaiza/payment_gateway
#     networks:
#       - payment
#     secrets:
#       - payment_token

# networks:
#   front-tier:
#   back-tier:
#   payment:
#     driver: overlay
#     attachable: true

# secrets:
#   postgres_password:
#     file: ./devsecrets/postgres_password
#   payment_token:
#     file: ./devsecrets/payment_token


version: "3.1"

services:
  reverse_proxy:
    build: ./reverse_proxy
    image: knire257/atsea-shop:atsea_reverse_proxy
    user: nginx

  database:
    
    build: 
       context: ./database
    image: knire257/atsea-shop:atsea_db
    user: postgres
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    ports:
      - "5432:5432" 
    networks:
      - back-tier
    secrets:
      - postgres_password

  appserver:
    image: knire257/atsea-shop:atsea_app
    build:
       context: app
       dockerfile: Dockerfile
    user: gordon
    ports:
      - "8080:8080" 
      - "5005:5005"
    networks:
      - front-tier
      - back-tier
    secrets:
      - postgres_password

  payment_gateway:
    image: knire257/atsea-shop:atsea_payment_gateway
    build:
      context: payment_gateway
    networks:
      - payment
    secrets:
      - payment_token

networks:
  front-tier:
  back-tier:
  payment:
    driver: overlay
 
secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
  payment_token:
    file: ./devsecrets/payment_token
