name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        context: [app, database, payment_gateway, reverse_proxy]
        
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and Push the images
      uses: docker/build-push-action@v2
      with: 
        context: ./${{ matrix.context }}
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/${{ matrix.context }}:latest, ${{secrets.DOCKER_USERNAME}}/${{ matrix.context }}:${{ github.sha }} 
  
